name: supabasechat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  clipboard: ^0.1.2+8
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  shared_preferences: ^0.5.12+4
  supabase: ^0.0.1-dev.9
  timeago: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  uses-material-design: true
